### ISSUE TITLE
Installing on Plesk

### ISSUE THREAD

**Issue by WizardKid** [cortezaproject/corteza-server#109]
Hi I am installing this app on Plesk. However, I realized there aren't any information on this platform

**Comment by darh** [comment]
That's correct. We do not officially support Plesk platform yet. It's in our backlog but I can not give you any exact dates.

**Comment by zayn008** [comment]
^ You could run it through Docker on Plesk and use the docker proxy to connect it to a domain

**Comment by tjerman** [comment]
@darh I think it would make sense to add this to the docs if someone else is interested in it. @zayn008 could you help me out here and provide a step-by-step (screenshots are also welcome) so I can integrate it into the docs? I've never used Plesk before so I'm a bit lost here..

**Comment by zayn008** [comment]
@tjerman I ended up moving my server over to Virtualmin, but let me see if I can get Plesk running on a VM and replicate my steps, it's a bit difficult because Plesk basically takes over the filesystem of Linux which isn't very practical for administration

I encountered a few bugs, the biggest one being each time my server reboots and/or the docker container, all the data was lost and I was back to square one. So it's certainly not a method for production but it could help speed up full support for Plesk, might also be worth getting input from their community on this

**Comment by darh** [comment]
Closed due to inactivity.
