### ISSUE TITLE
Office 365 / Azure AD login

### ISSUE THREAD

**Issue by zayn008** [cortezaproject/corteza-server#139]
Any chance for supporting login with O365 / Azure AD? Given it should run off existing parameters used for other login providers, this is nice for admins as we easily restrict O365 to domains/users which can then login to Corteza

**Comment by darh** [comment]
There are big changes re. authentication coming in `2021.3` release. Please take look at `....feature-oauth2` branch and see if you can add it on your own (should fit right next to github, google and other external oauth2 providers since we use `github.com/markbates/goth` to handle this.

If you can make an implementation I don't have a problem including it. 
If not, you'll have to wait a bit. But no later than 2021.6.

**Comment by anborg** [comment]
I'm assuming ....feature-oauth2 , would be more generic, and cover keycloak etc. Instead of one that is specific to Microsoft/AD.

**Comment by zayn008** [comment]
it's strange because in this [Installation Guide](https://cortezaproject.org/documentation/installation-guide/?s=) under 2.5 it says I can use any OpenID provider (Azure Supports OpenID), but I am running the latest version of Corteza 2020.12 and this is not an option to be found anywhere... unless im missing something?

**Comment by zayn008** [comment]
I did have a look at the code as I've implemented AzureAD authentication with PHP and Python so thought I could give it a shot, but I couldn't find the `...feature-oauth2` branch

**Comment by darh** [comment]
`feature-oauth2` branch was merged into `2021.3.x`.

You can branch out `2021.3.x` (or `2021.6.x`) and start there.

**Comment by splack** [comment]
@zayn008 you might be able to use OIDC with Azure AD and avoid the need to code it. Check out https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

**Comment by splack** [comment]
I tested OIDC with an Azure AD instance and it does indeed work. Thanks @darh and team.
