### ISSUE TITLE
Application name not visible in Safari (ver 2021.3)

### ISSUE THREAD

**Issue by micebrain** [cortezaproject/corteza-server#166]
The application name is not showing up in Safari, it works in Chrome. 

<img width="965" alt="Screenshot 2021-04-10 at 19 51 05" src="https://user-images.githubusercontent.com/7136209/114279725-68acd200-9a36-11eb-94c9-aada31c5a914.png">

**Comment by zmija** [comment]
hi @micebrain, thanks for reporting this. It was just fixed in https://github.com/cortezaproject/corteza-webapp-one/commit/5682181055990c93b6431851856f5e4da769a1cf

If you're using Corteza in Safari and notice anything unusual - please shout because, to be completely honest, Safari is the least tested browser from our side.

Cheers!
