### ISSUE TITLE
Multi-tenanting

### ISSUE THREAD

**Issue by akshaykumararavindan** [cortezaproject/corteza-server#174]
**Is your feature request related to a problem? Please describe.**
Multi-tenanting, as the name of the feature request suggests, would it be possible to build a multi-tenanting (using the same instance for different customers) system with Corteza?

**Describe the solution you'd like**
A single instance of the CRM which would be used by different organizations/companies reducing the overhead of multiple deployments.

If it is not on the roadmap of list of things to be done how would I approach it as a feature update.

**Comment by darh** [comment]
This is not on the roadmap and quite hard to implement due to architectural decisions that we made in the past. I would strongly advise against pursuing this.

Where do you see the overhead with multiple deployments?
In my opinion benefits in form of greater control, flexibility and security outweigh it.

**Comment by akshaykumararavindan** [comment]
> Where do you see the overhead with multiple deployments?

I felt that having a single instance of the server and then having multiple databases that serve for different sets of organizations would be easy to manage, I might be wrong.

**Comment by splack** [comment]
The modern multi-tenant architecture is to use software that manages containers and databases. Kubernetes (https://kubernetes.io/) is an option for managing multiple containers in a production environment. I've used GKE and google virtual machine instances with Container OS to run Corteza images backed by Google SQL (PostgreSQL).

I would prefer developer effort be devoted to making hosting multiple instances easier (Kubernetes operator? Scylladb support?) rather than building multi tenancy into the existing software. E,g, https://postgres-operator.readthedocs.io/en/latest/

Nearly all multi tenant architectures suffer from cross tenant isolation issues. Think about if one tenant was to overload the system by, for example, exposing their API to an internet service which did not rate limit or building workflows that were too resource intensive. There are too many corner cases to handle unless you have base resource (CPU, memory, IOPS, network) segregation.

Cloud services have made hosting multiple instances of things very cheap and easy. When compared the development effort required to design and implement multi tenancy with good isolation it doesn't make sense to duplicate something like Kubernetes these days.

Just my personal opinion.

**Comment by darh** [comment]
I agree with you 100% @splack! 
Stay tuned ;)
