### ISSUE TITLE
possible to change from go-chi to gofiber?

### ISSUE THREAD

**Issue by superdolt** [cortezaproject/corteza-server#248]
https://github.com/smallnest/go-web-framework-benchmark

fiber is more popular now
https://github.com/gofiber/fiber

**Comment by darh** [comment]
Thank you for your suggestion.

Unfortunately we can not just change and jump to a different lib just because it's shinny, new and popular :)
Chi solves all our problems right now. I'm keeping an eye on that benchmark repo.

However, the fastest framework might not be the best choice for Corteza. Although performance of the HTTP request handling is important it only adds a tiny tax to the overall request handling time.

I might reconsider the framework choice next time we're doing a big refactoring in that area: we need to (properly) support OpenAPI definitions and generate our handlers from that.

Hope this answers your question.
