### ISSUE TITLE
minio storage not initialising

### ISSUE THREAD

**Issue by andre-vspry** [cortezaproject/corteza-server#295]
**Describe the bug**
Set the various minio_ variables pointing to a bucket and corteza serve-api exits with error.

**To Reproduce**

```go
package main

import (
	"bytes"
	"log"

	"github.com/cortezaproject/corteza-server/pkg/objstore/minio"
)

func main() {
	m, err := minio.New("test-4/system", minio.Options{
		Endpoint:        "storage.googleapis.com",
		Secure:          true,
		AccessKeyID:     "GOOG1EXXXXXX",
		SecretAccessKey: "XXXXXXXX",
	})
	if err != nil {
		log.Fatal(err)
	}

	b := bytes.NewBuffer([]byte("test"))
	if err := m.Save("test", b); err != nil {
		log.Fatal(err)
	}
}
```

**Expected behavior**
corteza starts serving the API.

**Screenshots**
```
Nov 23 09:52:44 test-4 systemd[1]: Started Corteza low code server.
Nov 23 09:52:44 test-4 corteza-start[7205]: {"level":"warn","ts":1637625164.3658867,"msg":"loading plugins","paths":""}
Nov 23 09:52:44 test-4 corteza-start[7205]: {"level":"warn","ts":1637625164.3659208,"msg":"loading plugins","paths":[]}
Nov 23 09:52:44 test-4 corteza-start[7205]: Error: Bucket name contains invalid characters
Nov 23 09:52:44 test-4 corteza-start[7205]: Usage:
Nov 23 09:52:44 test-4 corteza-start[7205]:   corteza-server serve-api [flags]
Nov 23 09:52:44 test-4 corteza-start[7205]: Aliases:
Nov 23 09:52:44 test-4 corteza-start[7205]:   serve-api, serve
Nov 23 09:52:44 test-4 corteza-start[7205]: Flags:
Nov 23 09:52:44 test-4 corteza-start[7205]:   -h, --help   help for serve-api
Nov 23 09:52:44 test-4 corteza-start[7205]: Bucket name contains invalid characters
Nov 23 09:52:44 test-4 systemd[1]: corteza.service: Main process exited, code=exited, status=1/FAILURE
```

**Additional context**
Looks like the path is being added to the bucket name which causes it to fail the validity checks.

https://github.com/cortezaproject/corteza-server/blob/c5b730b524a91d5cac997c7aa252c8f276825854/system/service/service.go#L132

https://github.com/cortezaproject/corteza-server/blob/c5b730b524a91d5cac997c7aa252c8f276825854/compose/service/service.go#L110

```
	if DefaultObjectStore == nil {
		const svcPath = "system"
		if c.Storage.MinioEndpoint != "" {
			var bucket = svcPath
			if c.Storage.MinioBucket != "" {
				bucket = c.Storage.MinioBucket + c.Storage.MinioBucketSep + svcPath
			}

			DefaultObjectStore, err = minio.New(c.Storage.MinioBucket, minio.Options{
```

**Comment by vicpatel** [comment]
Thank you for reporting the issue, I will look into it.

**Comment by vicpatel** [comment]
Hey @andre-vspry,

As per the above example, In bucket name you have  "/" and that is causing the error `Bucket name contains invalid characters`, It is expected as per amazon bucket naming rules: **Bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-).**

Here are tests for bucket names from [MinIO Go SDK](https://github.com/minio/minio-go/blob/master/utils_test.go#L289).

Reference to a func [line](https://github.com/minio/minio-go/blob/master/pkg/s3utils/utils.go#L355) from MinIO Go SDK which returns `Bucket name contains invalid characters` error.


For more info, visit this link [AmazonS3 Bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html).

**Comment by andre-vspry** [comment]
@vicpatel I think I might not have explained the issues well. If I set the minio environment variables the server fails to start. I think this is because the bucket name has /system added by the code which works fine for local storage but not for object storage on S3. Have a read over the additional context section again from my bug report.

I think I referenced the wrong line too. Have a look at https://github.com/cortezaproject/corteza-server/blob/c5b730b524a91d5cac997c7aa252c8f276825854/compose/service/service.go#L113

**Comment by andre-vspry** [comment]
@darh is @vicpatel on this? It's been a while and I've not had any feedback.

**Comment by vicpatel** [comment]
Apologies, I should have pointed this right away, but Could you please attach `minio_` env variables with values except for `MINIO_ACCESS_KEY`, `MINIO_SECRET_KEY`.

The problem is with `MINIO_BUCKET_SEP` option, as per the amazon bitbucket naming rule it should only accept: lowercase letters, numbers, dot (.), and hyphen (-).

I believe when we set `MINIO_BUCKET_SEP=/`(or other than above mentioned) that will result in `${bucketName}${MINIO_BUCKET_SEP}${someString}` IE. `test/system`, that's an invalid bucket name.

Thank you for the pull request, appreciate it, sorry to say this but it creates more problems than it solves.
Changes will only work if `MINIO_BUCKET_SEP` is `/` otherwise it will fail, since we are using `MINIO_BUCKET_SEP` when we save object then it will create a path inside bucket.

**Comment by andre-vspry** [comment]
"MINIO_BUCKET" = "test-4";
          "MINIO_ENDPOINT" = "storage.googleapis.com";
          "MINIO_SECURE" = "true";

**Comment by andre-vspry** [comment]
Can you please elaborate on the problems my pull request creates? I'd like to get this fixed and will code whatever is needed to get the PR accepted. If you could describe the expected behaviour I will implement tests.

I'd like to get this moving as it's been 3 weeks and I still don't know what more I can do.

@darh perhaps you can prorvide some actionable feedback?

**Comment by vicpatel** [comment]
Hey @andre-vspry,
I am a bit afraid that the solution in PR, will break existing MinIo paths so I will add some tests to elaborate on the problem.

**Comment by vicpatel** [comment]
I looked into the problem and found that there is a default value of `MINIO_BUCKET_SEP`, It is `/`.

https://github.com/cortezaproject/corteza-server/blob/ff00bb889d7b82b2c485adc77dc1bd273de87cd5/pkg/options/objectStore.yaml#L33-L36

I reviewed the PR again by keeping this in mind and I believe,
It will solve this problem and also correct me if I am wrong as per the solution 

**it will create a bucket(without any separator and service name)** 
https://github.com/cortezaproject/corteza-server/blob/f6a8a096d0cb4c9a492b05f965a1c1e4fa8a8253/pkg/objstore/minio/store.go#L68

**then it creates a path(using separator and service name) inside a bucket in order to save objects**.
https://github.com/cortezaproject/corteza-server/blob/f6a8a096d0cb4c9a492b05f965a1c1e4fa8a8253/pkg/objstore/minio/store.go#L115

Could you please provide more details on this, why it had to be done like that?

As per me, this will not work for any existing system buckets since those buckets are already created,
It will work while saving new objects but It will break all existing paths for update and delete.

However, what if we have another env variable in order to have more flexibility over bucket name 
IE. `MINIO_PATH_PREFIX` with expected value like `corteza-{component}`, `{component}`.

For keeping the same pattern of options please take a look at auth option:
https://github.com/cortezaproject/corteza-server/blob/ff00bb889d7b82b2c485adc77dc1bd273de87cd5/pkg/options/auth.yaml#L55-L56

**Comment by andre-vspry** [comment]
I don't think I was clear enough when I opened the issue.

I would like to use a single bucket for object storage. This is important as in most cloud environments there are limits to the number of buckets that can be created.

I'm guessing the **intent** of having object storage was to share state between running servers, with easy configuration (i.e. sane and error free defaults), in a single bucket on paths matching each subsystem, to avoid name clashes.

I think the **intent** of having the seperator exposed as an environment variable and defaulted to / was because it came that way from the underlying implementaition (s3/minio) and / is used for path seperation on most linux filesystems and s3 object storage. The error (Bucket name contains invalid characters) returned when using the minimal set of environment variables (i.e. MINIO_BUCKET) makes it almost impossible to use minio without reading the code. Because of this I suspect that there is no actual usage of object storage in the wild.

Without tests, I cannot tell what the **intent** of exposing the seperator was. I also think the **intent** of having "system" and "compose" seperated was to ensure that object names do not clash.

Since there is an abstraction for storing objects that has implementations for s3 and filesystem, I don't see why another abstraction (interface) is needed just for minio as you have implemented.

I agree that if my PR is merged **and** anyone **is** using minio variables, it would require moving objects and bucket name changes.

**Comment by vicpatel** [comment]
Thank you for providing the detail that helped me understand the problem.

I am okay with the solution as long as if we don't break the existing system but also solve the problem at hand,
Please allow me some time to think this through, meanwhile If you have any suggestions I am open to them.

**Comment by andre-vspry** [comment]
Please keep this open for now. I'd like another view on this.
