### ISSUE TITLE
Empty workflow window can't be closed

### ISSUE THREAD

**Issue by sashker** [cortezaproject/corteza-server#558]
Hello.

I'm not sure if this issue belongs to this app, and if it's an issue at all, but I think so.

When I create a new workflow, I get to the "Workflow Configuration" popup window. 
In this window the is no button like "Cancel" or "Close", end Esc also doesn't work.

So, the only option is to press the "Back" button in my browser and get back to the previous screen. But I think it's not such user-friendly, and it's better to have something visible.

**Comment by yonkov** [comment]
PR at https://github.com/cortezaproject/corteza/pull/585

**Comment by katrinDY** [comment]
time box changes that need to be added to hour-hour and a half. If  you're not done afterwards, please, ping me.

**Comment by yonkov** [comment]
## Changlelog

### What was fixed
When creating a workflow, the user opens a modal with a form that he needs to submit in order to create a workflow. However, once the modal opens, there is no other way out of it except for pressing the back button on the browser.

### How was fixed
A back button was added that simulates the back button behaviour of the browser.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is working as expected. I also added the CL entry. So @yonkov once you merge everything feel free to close this issue.
