### ISSUE TITLE
uploads error: Cannot read property 'progress' of undefined 

### ISSUE THREAD

**Issue by adamdecaf** [cortezaproject/corteza-server#76]
**Describe the bug**
I was trying to upload a few CSV files and when they error'd I was kicked out of the upload dialog to a javascript error: `Cannot read property 'progress' of undefined`

**To Reproduce**
Upload either of these files: 

Non-ASCII character? 
```
FirstName,LastName,Email,Company
P.g,ផល្លី),p...y@gmail.com,pp
```

Improper amount of commas
```
FirstName,LastName,Email,Company
R.n,H.r,,S.a, LLC.,Github/ach
```

**Expected behavior**
The uploads should either fail within the dialog or skip, but I don't think bailing out entirely is the correct move. 

**Screenshots**
<img width="446" alt="Screen Shot 2020-01-02 at 11 45 39 AM" src="https://user-images.githubusercontent.com/120951/71688848-867c8900-2d55-11ea-8abe-31c61d70eb42.png">

**Additional context**
When uploading I had "Cancel Import" selected, but after the error I'm forced to refresh the entire Corteza tab.

**Comment by ranjanmanish95** [comment]
hi adamdecaf,
There r improper amount of commas in your csv file. That's why u r getting that issue.
Steps (shortcut) to fix this:
1. Upload your csv into google sheets.
2. Import the data into any spreadsheet.
3. Now download that data in .csv(comma saperated values) format.
4. Again import the downloaded csv into corteza. It will be imported.

**Comment by adamdecaf** [comment]
Ah, thanks for the tip!
